### ISSUE TITLE
owo-ify issue

### ISSUE THREAD

**Issue by BDTaken** [kaloncpu57/discord-plugins#2]
Hello, I've noticed that owo-ify always deselects itself with each restart, which I believe is inhibiting me from enabling owo-ify by restarting BD. However, if that is not the case, upon selecting owo-ify in the plugins does not change text. Is there a specific way to enable this owo-ify plugin?

**Comment by kaloncpu57** [comment]
I'm about to completely rework the plugin. Some recent Discord updates completely broke it

**Comment by kaloncpu57** [comment]
I updated the plugin, but currently BetterDiscord is having issues with the recent Discord update.

For now you can use the unofficial fork to reinstall https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82

For future help, just go to https://betterdiscord.net/home/ and join the support server to ask about whatever is going on with BetterDiscord. (In fact you can do this now if you want to ask them and make sure that fork is safe)
