### ISSUE TITLE
Completely breaking issue. 

### ISSUE THREAD

**Issue by YaBoiSoviet** [kaloncpu57/discord-plugins#3]
I installed this plugin, and it works fine, changing l and r into w as i type, but as I hit enter, nothing happens. I tried reinstalling the plugin, restarting discord multiple times, and nothing. I apoligize if this is a user error, as I am new to using Better Discord.

**Comment by kaloncpu57** [comment]
Make sure Discord is updated. Currently, the BetterDiscord installer is not compatible with the latest version of Discord, so this fork is being used https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82

You can go to https://betterdiscord.net/home/ to join the support servers for BD and see when the new installer is ready.
