### ISSUE TITLE
owo-ify plugin won't allow sending messages

### ISSUE THREAD

**Issue by elterrasense** [kaloncpu57/discord-plugins#4]
Whenever I start the plugin if I try to send a message it just won't send. If for some reason the problem is the keyboard layout I use the spanish layout. I tried with English (US) just in case but it still didn't send messages.

**Comment by kaloncpu57** [comment]
Make sure Discord is updated. Currently, the BetterDiscord installer is not compatible with the latest version of Discord, so this fork is being used https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82

You can go to https://betterdiscord.net/home/ to join the support servers for BD and see when the new installer is ready.

**Comment by elterrasense** [comment]
Hmm... that's weird. I installed BD that same day without any problem and I do have the latest version of Discord. Anyways I'll try that.

**Comment by kaloncpu57** [comment]
Forgot to mention it here when I fixed it, but the plugin should definitely be working properly again. It no longer updates as you type, but will change the message when it's sent.
