### ISSUE TITLE
Greentext plugin no longer working.

### ISSUE THREAD

**Issue by Icarus77** [kaloncpu57/discord-plugins#5]
Latest Discord update seems to have broken the greentextr plugin for BD. Along with this, the orange text plugin that Arashiryuu made for when someone starts a post with "<" has ceased to function as well. Is it possible to update this?

**Comment by kaloncpu57** [comment]
I have nothing to do with, nor have I heard about, the orange text plugin, but...

I fixed the greentext plugin (along with the Hex Color Preview plugin) for the Discord update, and added an auto-updater to the greentext plugin. Thanks for the heads up.

**Comment by Icarus77** [comment]
Downloaded the update. Does not seem to work when initially typed, but the text turns green when you switch channels/servers and then go back to the channel the message was typed in.

Any ideas why? Also would it be possible for me to just modify a couple of lines to recreate the "orangetext" plugin? Like copying the greentext plugin file changing the ">" to a "<" and the green hex to an orange one?
